// Base de datos de organismos del arrecife de coral
const ORGANISMS_DATA = [
    {
        id: 1,
        commonName: 'Pez Payaso',
        scientificName: 'Amphiprion ocellaris',
        emoji: '🐠',
        color: '#FF6B35',
        size: 'Pequeño (8-10 cm)',
        cites: 'No CITES',
        minCatchSize: 'N/A',
        behavior: 'Vive en simbiosis con anémonas de mar. Es muy territorial y agresivo con otros peces de su especie.',
        curiosity: '¡El pez payaso puede cambiar de sexo! Si la hembra muere, el macho dominante se convierte en hembra para reproducirse.',
        habitat: 'Arrecifes de coral del Indo-Pacífico',
        diet: 'Omnívoro (pequeños crustáceos, algas, detritos)',
        speed: 3
    },
    {
        id: 2,
        commonName: 'Pez Cirujano Azul',
        scientificName: 'Paracanthurus hepatus',
        emoji: '🐟',
        color: '#0066FF',
        size: 'Mediano (20-25 cm)',
        cites: 'No CITES',
        minCatchSize: 'N/A',
        behavior: 'Pez activo que vive en grupos. Se alimenta durante el día en las zonas rocosas del arrecife.',
        curiosity: 'Tiene espinas venenosas en la cola que utiliza como defensa. ¡Se conoce como "Tang Azul"!',
        habitat: 'Arrecifes de coral indopacíficos',
        diet: 'Principalmente algas (herbívoro)',
        speed: 2
    },
    {
        id: 3,
        commonName: 'Raya Manta',
        scientificName: 'Manta birostris',
        emoji: '🦼',
        color: '#2E2E2E',
        size: 'Grande (4-7 m)',
        cites: 'Apéndice II CITES',
        minCatchSize: 'No especificado',
        behavior: 'Viaja en grandes grupos llamados "escuelas". Realiza acrobacias fuera del agua.',
        curiosity: 'Tiene el cerebro más grande de todos los peces. ¡Puede saltar hasta 2 metros fuera del agua!',
        habitat: 'Aguas tropicales y templadas de arrecifes',
        diet: 'Filtrador (zooplancton, huevos de peces)',
        speed: 2
    },
    {
        id: 4,
        commonName: 'Pez León',
        scientificName: 'Pterois volitans',
        emoji: '🦁',
        color: '#FF4500',
        size: 'Mediano (30-38 cm)',
        cites: 'No CITES',
        minCatchSize: 'N/A',
        behavior: 'Cazador nocturno que permanece inmóvil durante el día. Altamente venenoso.',
        curiosity: 'Sus aletas tienen veneno neurotóxico extremadamente potente. Una espina puede causar dolor intenso en humanos.',
        habitat: 'Arrecifes de coral del Indo-Pacífico',
        diet: 'Carnívoro (peces pequeños, camarones)',
        speed: 1
    },
    {
        id: 5,
        commonName: 'Tortuga Marina',
        scientificName: 'Chelonia mydas',
        emoji: '🐢',
        color: '#228B22',
        size: 'Grande (80-110 cm)',
        cites: 'Apéndice I CITES - EN PELIGRO',
        minCatchSize: 'Protegida',
        behavior: 'Migra miles de km entre zonas de alimentación y reproducción. Es muy lenta pero resistente.',
        curiosity: 'Las tortugas marinas pueden vivir más de 100 años. ¡Las hembras siempre regresan a la playa donde nacieron para desovar!',
        habitat: 'Océanos tropicales y subtropicales',
        diet: 'Omnívoro (algas, invertebrados, especialmente medusas)',
        speed: 1
    },
    {
        id: 6,
        commonName: 'Pez Loro Arcoíris',
        scientificName: 'Scarus guacamaia',
        emoji: '🦜',
        color: '#FF1493',
        size: 'Grande (76-92 cm)',
        cites: 'No CITES',
        minCatchSize: '30-36 cm',
        behavior: 'Vive en solitario o en parejas. Es muy activo durante el día.',
        curiosity: 'Come coral y excreta arena de la que está hecho 70% de las playas tropicales. ¡Un solo pez puede producir toneladas de arena al año!',
        habitat: 'Arrecifes de coral del Atlántico Occidental',
        diet: 'Herbívoro (algas y coral duro)',
        speed: 2
    },
    {
        id: 7,
        commonName: 'Caballito de Mar',
        scientificName: 'Hippocampus kuda',
        emoji: '🐴',
        color: '#FFD700',
        size: 'Muy Pequeño (15-30 cm)',
        cites: 'Apéndice II CITES',
        minCatchSize: 'Protegido',
        behavior: 'Se mueve lentamente agarrado a plantas marinas. Es monógamo.',
        curiosity: '¡El macho es quien da a luz! Lleva los huevos en una bolsa especial durante el embarazo.',
        habitat: 'Aguas costeras poco profundas',
        diet: 'Carnívoro (pequeños crustáceos)',
        speed: 0.5
    },
    {
        id: 8,
        commonName: 'Coral Cerebro',
        scientificName: 'Diploria strigosa',
        emoji: '🧠',
        color: '#8B4513',
        size: 'Variable',
        cites: 'Apéndice II CITES',
        minCatchSize: 'Protegido',
        behavior: 'Sedentario. Vive en colonias que pueden durar siglos.',
        curiosity: 'Los corales son animales, no plantas. Generan su propio alimento mediante algas simbióticas llamadas zooxantelas.',
        habitat: 'Arrecifes de coral del Caribe',
        diet: 'Zooxantelas y zooplancton',
        speed: 0
    },
    {
        id: 9,
        commonName: 'Pulpo de Arrecife',
        scientificName: 'Octopus cyanea',
        emoji: '🐙',
        color: '#8B0000',
        size: 'Pequeño a Mediano (15-20 cm)',
        cites: 'No CITES',
        minCatchSize: 'N/A',
        behavior: 'Nocturno y solitario. Cambista de color experto.',
        curiosity: 'Tiene 3 corazones y sangre azul. Puede cambiar de color en milisegundos. ¡Es extremadamente inteligente!',
        habitat: 'Arrecifes de coral del Indo-Pacífico',
        diet: 'Carnívoro (cangrejos, camarones, peces)',
        speed: 2
    },
    {
        id: 10,
        commonName: 'Erizo de Mar',
        scientificName: 'Diadema antillarum',
        emoji: '🌰',
        color: '#000000',
        size: 'Pequeño (5-7 cm)',
        cites: 'No CITES',
        minCatchSize: 'N/A',
        behavior: 'Se esconde en grietas durante el día. Sale a alimentarse por la noche.',
        curiosity: 'Sus púas tienen veneno. Si se clavan en la piel humana, pueden causar dolor intenso. ¡Tienen 5 ojos además de los ocelos!',
        habitat: 'Arrecifes de coral tropicales',
        diet: 'Herbívoro (algas, detritos)',
        speed: 0.5
    }
];

// Configuración del acuario
const AQUARIUM_CONFIG = {
    width: 1000,
    height: 600,
    particleCount: 15,
    bubbleCount: 20,
    backgroundColor: '#001a33',
    particleSpeed: 1
};